<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeSectionSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $sections = [
            [
                'id' => 1,
                'website_id' => 1,
                'parent_id' => null,
                'title_th' => 'คณะผู้บริหารมหาวิทยาลัยราชภัฏพระนครศรีอยุธยา',
                'slug' => 'university-executives',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'website_id' => 2,
                'parent_id' => null,
                'title_th' => 'ผู้บริหาร',
                'slug' => 'executives',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'ผู้บริหาร',
                'slug' => 'executives',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานบริหารงานทั่วไป',
                'slug' => 'general-administration',
                'section_type' => 'group',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานการเงินและบัญชี',
                'slug' => 'finance-accounting',
                'section_type' => 'group',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานกิจการสภามหาวิทยาลัย',
                'slug' => 'university-council-affairs',
                'section_type' => 'group',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานทรัพยากรบุคคล',
                'slug' => 'human-resources',
                'section_type' => 'group',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานนิติการ',
                'slug' => 'legal-affairs',
                'section_type' => 'group',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานบริการวิชาการและจัดหารายได้',
                'slug' => 'academic-service-income',
                'section_type' => 'group',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานพัสดุ',
                'slug' => 'supplies',
                'section_type' => 'group',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'งานอาคารสถานที่และภูมิสถาปัตย์',
                'slug' => 'building-landscape',
                'section_type' => 'group',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'งานวิศวกรรมและภูมิสถาปัตย์',
                'slug' => 'engineering-landscape',
                'section_type' => 'subgroup',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'งานอาคารสถานที่และซ่อมบำรุง',
                'slug' => 'building-maintenance',
                'section_type' => 'subgroup',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'งานไฟฟ้า-ประปา',
                'slug' => 'electricity-water',
                'section_type' => 'subgroup',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'งานภาคพื้นดิน',
                'slug' => 'ground-service',
                'section_type' => 'subgroup',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'งานซ่อมสร้าง',
                'slug' => 'construction-repair',
                'section_type' => 'subgroup',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'ยานพาหนะ',
                'slug' => 'vehicles',
                'section_type' => 'subgroup',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'website_id' => 3,
                'parent_id' => 11,
                'title_th' => 'คนงาน',
                'slug' => 'workers',
                'section_type' => 'subgroup',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'website_id' => 3,
                'parent_id' => null,
                'title_th' => 'ศูนย์ดิจิทัลเพื่อเรียนรู้และสื่อสารองค์กร',
                'slug' => 'digital-learning-communication-center',
                'section_type' => 'group',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'website_id' => 5,
                'parent_id' => null,
                'title_th' => 'ผู้บริหารและบุคลากร',
                'slug' => 'executives-and-personnel',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'website_id' => 4,
                'parent_id' => null,
                'title_th' => 'ผู้บริหาร',
                'slug' => 'executives',
                'section_type' => 'executive',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'website_id' => 4,
                'parent_id' => null,
                'title_th' => 'งานส่งเสริมวิชาการ',
                'slug' => 'academic-promotion',
                'section_type' => 'group',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'website_id' => 4,
                'parent_id' => null,
                'title_th' => 'งานบริการการศึกษา',
                'slug' => 'educational-services',
                'section_type' => 'group',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'website_id' => 6,
                'parent_id' => null,
                'title_th' => 'ผู้บริหารและบุคลากร',
                'slug' => 'executives-and-personnel',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'website_id' => 7,
                'parent_id' => null,
                'title_th' => 'คณะผู้บริหาร',
                'slug' => 'faculty-executives',
                'section_type' => 'executive',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'website_id' => 7,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายวิชาการ',
                'slug' => 'academic-staff',
                'section_type' => 'group',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาคณิตศาสตร์',
                'slug' => 'mathematics',
                'section_type' => 'subgroup',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาวิทยาศาสตร์',
                'slug' => 'science',
                'section_type' => 'subgroup',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาสังคมศึกษา',
                'slug' => 'social-studies',
                'section_type' => 'subgroup',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาการศึกษาปฐมวัย',
                'slug' => 'early-childhood-education',
                'section_type' => 'subgroup',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาคอมพิวเตอร์ศึกษา',
                'slug' => 'computer-education',
                'section_type' => 'subgroup',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาพลศึกษา',
                'slug' => 'physical-education',
                'section_type' => 'subgroup',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาการสอนภาษาไทย',
                'slug' => 'thai-language-teaching',
                'section_type' => 'subgroup',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาการสอนภาษาอังกฤษ',
                'slug' => 'english-language-teaching',
                'section_type' => 'subgroup',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาการประถมศึกษา',
                'slug' => 'elementary-education',
                'section_type' => 'subgroup',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'สาขาวิชาการศึกษาพิเศษ',
                'slug' => 'special-education',
                'section_type' => 'subgroup',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'website_id' => 7,
                'parent_id' => 26,
                'title_th' => 'กลุ่มวิชาชีพครู',
                'slug' => 'teaching-profession',
                'section_type' => 'subgroup',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'website_id' => 7,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายสนับสนุนวิชาการ',
                'slug' => 'academic-support-staff',
                'section_type' => 'group',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'website_id' => 8,
                'parent_id' => null,
                'title_th' => 'คณะกรรมการ',
                'slug' => 'committee',
                'section_type' => 'group',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'website_id' => 8,
                'parent_id' => 39,
                'title_th' => 'คณะกรรมการประจำคณะ',
                'slug' => 'faculty-committee',
                'section_type' => 'subgroup',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'website_id' => 8,
                'parent_id' => 39,
                'title_th' => 'คณะกรรมการบริหารคณะ',
                'slug' => 'faculty-executive-committee',
                'section_type' => 'subgroup',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'website_id' => 8,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายวิชาการ',
                'slug' => 'academic-staff',
                'section_type' => 'group',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'website_id' => 8,
                'parent_id' => 42,
                'title_th' => 'ภาควิชามนุษยศาสตร์',
                'slug' => 'humanities-department',
                'section_type' => 'group',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาภาษาอังกฤษ',
                'slug' => 'english',
                'section_type' => 'subgroup',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาภาษาญี่ปุ่น',
                'slug' => 'japanese',
                'section_type' => 'subgroup',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาภาษาไทย',
                'slug' => 'thai-language',
                'section_type' => 'subgroup',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชานาฏศิลป์ศึกษา',
                'slug' => 'dramatic-arts-education',
                'section_type' => 'subgroup',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาดนตรีสร้างสรรค์',
                'slug' => 'creative-music',
                'section_type' => 'subgroup',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาศิลปศึกษา',
                'slug' => 'art-education',
                'section_type' => 'subgroup',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาสหวิทยาการเพื่อการจัดการฮาลาล',
                'slug' => 'interdisciplinary-halal-management',
                'section_type' => 'subgroup',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาภาษาจีน',
                'slug' => 'chinese',
                'section_type' => 'subgroup',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'website_id' => 8,
                'parent_id' => 43,
                'title_th' => 'สาขาวิชาดนตรีศึกษา',
                'slug' => 'music-education',
                'section_type' => 'subgroup',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'website_id' => 8,
                'parent_id' => 42,
                'title_th' => 'ภาควิชาสังคมศาสตร์',
                'slug' => 'social-sciences-department',
                'section_type' => 'group',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชารัฐประศาสนศาสตร์',
                'slug' => 'public-administration',
                'section_type' => 'subgroup',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชาการพัฒนาชุมชนและสังคม',
                'slug' => 'community-and-social-development',
                'section_type' => 'subgroup',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชานิเทศศาสตร์ดิจิทัล',
                'slug' => 'digital-communication-arts',
                'section_type' => 'subgroup',
                'sort_order' => 18,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชานิติศาสตร์',
                'slug' => 'law',
                'section_type' => 'subgroup',
                'sort_order' => 19,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชาประวัติศาสตร์',
                'slug' => 'history',
                'section_type' => 'subgroup',
                'sort_order' => 20,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'website_id' => 8,
                'parent_id' => 53,
                'title_th' => 'สาขาวิชาการจัดการรัฐกิจและการปกครองท้องถิ่น',
                'slug' => 'public-affairs-and-local-government',
                'section_type' => 'subgroup',
                'sort_order' => 21,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'website_id' => 8,
                'parent_id' => 42,
                'title_th' => 'กลุ่มวิชา',
                'slug' => 'subject-groups',
                'section_type' => 'group',
                'sort_order' => 22,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'website_id' => 8,
                'parent_id' => 60,
                'title_th' => 'วิชาภูมิศาสตร์',
                'slug' => 'geography',
                'section_type' => 'subgroup',
                'sort_order' => 23,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'website_id' => 8,
                'parent_id' => 60,
                'title_th' => 'วิชาปรัชญาและศาสนา',
                'slug' => 'philosophy-and-religion',
                'section_type' => 'subgroup',
                'sort_order' => 24,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'website_id' => 8,
                'parent_id' => 60,
                'title_th' => 'วิชาบรรณารักษศาสตร์',
                'slug' => 'library-science',
                'section_type' => 'subgroup',
                'sort_order' => 25,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'website_id' => 9,
                'parent_id' => null,
                'title_th' => 'คณะกรรมการ',
                'slug' => 'committee',
                'section_type' => 'group',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'website_id' => 9,
                'parent_id' => 64,
                'title_th' => 'คณะกรรมการประจำคณะ',
                'slug' => 'faculty-committee',
                'section_type' => 'subgroup',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'website_id' => 9,
                'parent_id' => 64,
                'title_th' => 'ผู้บริหารคณะ',
                'slug' => 'faculty-executives',
                'section_type' => 'executive',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'website_id' => 9,
                'parent_id' => null,
                'title_th' => 'ภาควิชาวิทยาศาสตร์',
                'slug' => 'science-department',
                'section_type' => 'group',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'เคมี',
                'slug' => 'chemistry',
                'section_type' => 'subgroup',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'วิทยาการคอมพิวเตอร์',
                'slug' => 'computer-science',
                'section_type' => 'subgroup',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'จุลชีววิทยา',
                'slug' => 'microbiology',
                'section_type' => 'subgroup',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'คณิตศาสตร์ประยุกต์',
                'slug' => 'applied-mathematics',
                'section_type' => 'subgroup',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'เทคโนโลยีสารสนเทศ',
                'slug' => 'information-technology',
                'section_type' => 'subgroup',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'เทคโนโลยีสิ่งแวดล้อม',
                'slug' => 'environmental-technology',
                'section_type' => 'subgroup',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'วิทยาศาสตร์ศึกษา (แขนงวิชาฟิสิกส์)',
                'slug' => 'science-education-physics',
                'section_type' => 'subgroup',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'วิทยาศาสตร์ศึกษา (แขนงวิชาเคมี)',
                'slug' => 'science-education-chemistry',
                'section_type' => 'subgroup',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'website_id' => 9,
                'parent_id' => 67,
                'title_th' => 'วิทยาศาสตร์ศึกษา (แขนงวิชาชีววิทยา)',
                'slug' => 'science-education-biology',
                'section_type' => 'subgroup',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'website_id' => 9,
                'parent_id' => null,
                'title_th' => 'ภาควิชาวิทยาศาสตร์ประยุกต์',
                'slug' => 'applied-science-department',
                'section_type' => 'group',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'เกษตรศาสตร์',
                'slug' => 'agriculture',
                'section_type' => 'subgroup',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'วิทยาศาสตร์และการจัดการเทคโนโลยีอาหาร',
                'slug' => 'food-science-and-technology-management',
                'section_type' => 'subgroup',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'อาชีวอนามัยและความปลอดภัย',
                'slug' => 'occupational-health-and-safety',
                'section_type' => 'subgroup',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'วิศวกรรมไฟฟ้า',
                'slug' => 'electrical-engineering',
                'section_type' => 'subgroup',
                'sort_order' => 18,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'วิศวกรรมปัญญาประดิษฐ์ (ต่อเนื่อง)',
                'slug' => 'artificial-intelligence-engineering-continuing',
                'section_type' => 'subgroup',
                'sort_order' => 19,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'เทคโนโลยีอุตสาหกรรม (วิชาเอก เทคโนโลยีระบบควบคุมการผลิตอัตโนมัติ)',
                'slug' => 'industrial-technology-automation-control-systems',
                'section_type' => 'subgroup',
                'sort_order' => 20,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'เทคโนโลยีอุตสาหกรรม (วิชาเอก การจัดการเทคโนโลยีอุตสาหกรรม)',
                'slug' => 'industrial-technology-management',
                'section_type' => 'subgroup',
                'sort_order' => 21,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'คหกรรมศาสตร์',
                'slug' => 'home-economics',
                'section_type' => 'subgroup',
                'sort_order' => 22,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'เทคโนโลยีการเกษตรสมัยใหม่',
                'slug' => 'modern-agricultural-technology',
                'section_type' => 'subgroup',
                'sort_order' => 23,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'วิศวกรรมการจัดการ',
                'slug' => 'management-engineering',
                'section_type' => 'subgroup',
                'sort_order' => 24,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'website_id' => 9,
                'parent_id' => 77,
                'title_th' => 'สาธารณสุขศาสตร์',
                'slug' => 'public-health',
                'section_type' => 'subgroup',
                'sort_order' => 25,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'website_id' => 9,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายสนับสนุน',
                'slug' => 'support-staff',
                'section_type' => 'group',
                'sort_order' => 26,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'website_id' => 10,
                'parent_id' => null,
                'title_th' => 'คณะกรรมการประจำคณะ',
                'slug' => 'faculty-committee',
                'section_type' => 'group',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'website_id' => 10,
                'parent_id' => null,
                'title_th' => 'คณะกรรมการบริหารคณะ',
                'slug' => 'faculty-executive-committee',
                'section_type' => 'group',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'website_id' => 10,
                'parent_id' => null,
                'title_th' => 'คณะผู้บริหาร',
                'slug' => 'faculty-executives',
                'section_type' => 'executive',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'website_id' => 10,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายวิชาการ',
                'slug' => 'academic-staff',
                'section_type' => 'group',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการบัญชี',
                'slug' => 'accounting',
                'section_type' => 'subgroup',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการจัดการ',
                'slug' => 'management',
                'section_type' => 'subgroup',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการบริหารทรัพยากรมนุษย์',
                'slug' => 'human-resource-management',
                'section_type' => 'subgroup',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการตลาด',
                'slug' => 'marketing',
                'section_type' => 'subgroup',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาคอมพิวเตอร์ธุรกิจ',
                'slug' => 'business-computer',
                'section_type' => 'subgroup',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการจัดการโลจิสติกส์และซัพพลายเชน',
                'slug' => 'logistics-and-supply-chain-management',
                'section_type' => 'subgroup',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการท่องเที่ยวและบริการ',
                'slug' => 'tourism-and-hospitality',
                'section_type' => 'subgroup',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาการจัดการธุรกิจการค้าสมัยใหม่',
                'slug' => 'modern-trade-business-management',
                'section_type' => 'subgroup',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'website_id' => 10,
                'parent_id' => 93,
                'title_th' => 'สาขาวิชาบริหารธุรกิจ (MBA)',
                'slug' => 'business-administration-mba',
                'section_type' => 'subgroup',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'website_id' => 10,
                'parent_id' => null,
                'title_th' => 'บุคลากรสายสนับสนุนวิชาการ',
                'slug' => 'academic-support-staff',
                'section_type' => 'group',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'website_id' => 10,
                'parent_id' => 103,
                'title_th' => 'หัวหน้าสำนักงาน',
                'slug' => 'office-head',
                'section_type' => 'subgroup',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'website_id' => 10,
                'parent_id' => 103,
                'title_th' => 'งานบริหารงานทั่วไป',
                'slug' => 'general-administration',
                'section_type' => 'subgroup',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'website_id' => 10,
                'parent_id' => 103,
                'title_th' => 'งานวิชาการและพัฒนานักศึกษา',
                'slug' => 'academic-affairs-and-student-development',
                'section_type' => 'subgroup',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            
        ];

        DB::table('employee_sections')->upsert(
            $sections,
            ['id'],
            ['website_id', 'parent_id', 'title_th', 'slug', 'section_type', 'sort_order', 'is_active', 'updated_at']
        );
    }
}
