<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $aru = Department::where('code', 'aru')->first();

        $employees = [
            [
                'prefix_name_th' => 'รศ.ดร.',
                'first_name_th' => 'ธาตรี',
                'last_name_th' => 'มหันตรัตน์',
                'type' => 'academic',
                'position_name' => 'รองอธิการบดีฝ่ายบริหารทรัพยากร',
                'internal_phone' => '035-276555 ต่อ 1006',
                'email' => 'dhatreecu24@hotmail.com',
                'image' => null,
                'sort_order' => 1,
            ],
            [
                'prefix_name_th' => 'อาจารย์',
                'first_name_th' => 'จิรศักดิ์',
                'last_name_th' => 'ชุมวรานนท์',
                'type' => 'academic',
                'position_name' => 'รองอธิการบดีฝ่ายพัฒนานักศึกษาและเทคโนโลยีสารสนเทศ',
                'internal_phone' => '035-276555 ต่อ 1002',
                'email' => 'jirasak@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/jirasak.jpg',
                'sort_order' => 2,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'กรองทิพย์',
                'last_name_th' => 'เนียมถนอม',
                'type' => 'academic',
                'position_name' => 'รองอธิการบดีฝ่ายบริหารงานวิชาการ',
                'internal_phone' => '035-276555 ต่อ 1003',
                'email' => 'nkrongthip@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-090000.jpg',
                'sort_order' => 3,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'กมลวรรณ',
                'last_name_th' => 'วรรณธนัง',
                'type' => 'academic',
                'position_name' => 'รองอธิการบดีฝ่ายวิจัย นวัตกรรม และพัฒนาท้องถิ่น',
                'internal_phone' => '035-276555 ต่อ 1005',
                'email' => 'duean_2520@hotmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-090053.jpg',
                'sort_order' => 4,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'สุดารัตน์',
                'last_name_th' => 'เกลี้ยงสอาด',
                'type' => 'academic',
                'position_name' => 'รองอธิการบดีฝ่ายยุทธศาสตร์ แผนงานและกิจการสภามหาวิทยาลัย',
                'internal_phone' => '035-276555 ต่อ 1013',
                'email' => 'Sudarat_k@hotmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-090240.jpg',
                'sort_order' => 5,
            ],
            [
                'prefix_name_th' => 'ผศ.',
                'first_name_th' => 'ยุพิน',
                'last_name_th' => 'พวกยะ',
                'type' => 'academic',
                'position_name' => 'ผู้ช่วยอธิการบดีฝ่ายประกันคุณภาพการศึกษา',
                'internal_phone' => '035-276555 ต่อ 8082',
                'email' => 'pyupin@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-111637.jpg',
                'sort_order' => 6,
            ],
            [
                'prefix_name_th' => 'อาจารย์',
                'first_name_th' => 'นรินทร์',
                'last_name_th' => 'อุ่นแก้ว',
                'type' => 'academic',
                'position_name' => 'ผู้ช่วยอธิการบดีฝ่ายงานบริหารทั่วไปและกฎหมาย',
                'internal_phone' => '035-276555 ต่อ 1014',
                'email' => 'meeunkeaw0210@gmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-090143.jpg',
                'sort_order' => 7,
            ],
            [
                'prefix_name_th' => 'ผศ.',
                'first_name_th' => 'สุกัลยา',
                'last_name_th' => 'คงประดิษฐ์',
                'type' => 'academic',
                'position_name' => 'ผู้ช่วยอธิการบดีฝ่ายกิจการพิเศษ',
                'internal_phone' => '035-276555 ต่อ 8340',
                'email' => 'sukanlaya@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/sukanlaya_1.jpg',
                'sort_order' => 8,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'บริบูรณ์',
                'last_name_th' => 'ชอบทำดี',
                'type' => 'academic',
                'position_name' => 'คณบดีคณะครุศาสตร์',
                'internal_phone' => '035-322084 , 035-276581 ต่อ 4000',
                'email' => 'cboriboon@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-090404.png',
                'sort_order' => 9,
            ],
            [
                'prefix_name_th' => 'รศ.ดร.',
                'first_name_th' => 'ภาคิน',
                'last_name_th' => 'โชติเวศย์ศิลป์',
                'type' => 'academic',
                'position_name' => 'คณบดีคณะมนุษยศาสตร์และสังคมศาสตร์',
                'internal_phone' => '035-276555 ต่อ 4501',
                'email' => 'pakin@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/pakin.jpg',
                'sort_order' => 10,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'สุขรักษ์',
                'last_name_th' => 'แซ่เจี่ย',
                'type' => 'academic',
                'position_name' => 'คณบดีคณะวิทยาศาสตร์และเทคโนโลยี',
                'internal_phone' => '035-276555 ต่อ 5001',
                'email' => 'sukkharak@gmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/S__1353646762.jpg',
                'sort_order' => 11,
            ],
            [
                'prefix_name_th' => 'รศ.ดร.',
                'first_name_th' => 'อภิชาติ',
                'last_name_th' => 'พานสุวรรณ',
                'type' => 'academic',
                'position_name' => 'คณบดีบัณฑิตวิทยาลัย',
                'internal_phone' => '035-276555 ต่อ 7502',
                'email' => 'Apichat_asm@hotmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/apichat.jpg',
                'sort_order' => 12,
            ],
            [
                'prefix_name_th' => 'อาจารย์ ดร.',
                'first_name_th' => 'สมเกียรติ',
                'last_name_th' => 'แดงเจริญ',
                'type' => 'academic',
                'position_name' => 'คณบดีคณะวิทยาการจัดการ',
                'internal_phone' => '035-276555 ต่อ 8398',
                'email' => 'toatanu@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-092108.jpg',
                'sort_order' => 13,
            ],
            [
                'prefix_name_th' => 'ผศ.ดร.',
                'first_name_th' => 'เลิศชาย',
                'last_name_th' => 'สถิตย์พนาวงศ์',
                'type' => 'academic',
                'position_name' => 'ผู้อำนวยการสถาบันวิจัยและพัฒนา',
                'internal_phone' => '035-276555 ต่อ 2101',
                'email' => 'lerdchai99@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/2021-09-08-010539.png',
                'sort_order' => 14,
            ],
            [
                'prefix_name_th' => 'อาจารย์ ดร.',
                'first_name_th' => 'กันยาลักษณ์',
                'last_name_th' => 'โพธิ์ดง',
                'type' => 'academic',
                'position_name' => 'ผู้อำนวยการสำนักวิทยบริการและเทคโนโลยีสารสนเทศ',
                'internal_phone' => '035-276555 ต่อ 2501',
                'email' => 'pkanyalag@aru.ac.th',
                'image' => 'https://www.aru.ac.th/public/images_executive/jib7.jpg',
                'sort_order' => 15,
            ],
            [
                'prefix_name_th' => 'อาจารย์ ดร.',
                'first_name_th' => 'สุรินทร์',
                'last_name_th' => 'ศรีสังข์งาม',
                'type' => 'academic',
                'position_name' => 'ผู้อำนวยการสถาบันอยุธยาศึกษา',
                'internal_phone' => '035-276555 ต่อ 2301',
                'email' => 'surin.thaiart@gmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/2021-08-23-035735.png',
                'sort_order' => 16,
            ],
            [
                'prefix_name_th' => 'นาง',
                'first_name_th' => 'ลักขณา',
                'last_name_th' => 'เตชวงษ์',
                'type' => 'support',
                'position_name' => 'ผู้อำนวยการสำนักงานอธิการบดี',
                'internal_phone' => '035-276550 ต่อ 1015 และ 1000',
                'email' => 'tachawong.lakana@gmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/lakana.jpg',
                'sort_order' => 17,
            ],
            [
                'prefix_name_th' => 'อาจารย์ ดร.',
                'first_name_th' => 'นพดล',
                'last_name_th' => 'ปรางค์ทอง',
                'type' => 'academic',
                'position_name' => 'ประธานสภาคณาจารย์และข้าราชการ',
                'internal_phone' => '035-276555 ต่อ 1004',
                'email' => 'nopphadonpr@gmail.com',
                'image' => 'https://www.aru.ac.th/public/images_executive/2023-07-10-085907.jpg',
                'sort_order' => 18,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::updateOrCreate(
                ['email' => $employee['email']],
                [
                    'home_department_id' => $aru?->id,
                    'prefix_name_th' => $employee['prefix_name_th'],
                    'first_name_th' => $employee['first_name_th'],
                    'last_name_th' => $employee['last_name_th'],
                    'type' => $employee['type'],
                    'position_name' => $employee['position_name'],
                    'internal_phone' => $employee['internal_phone'],
                    'mobile_phone' => null,
                    'line_id' => null,
                    'image' => $employee['image'],
                    'sort_order' => $employee['sort_order'],
                    'is_active' => true,
                ]
            );
        }
    }
}